import { AppItem, DeviceInfo, ClipboardItem, ProcessInfo, MusicTrack, RemoteExecutable } from '../types/launcher';

export const DEVICE_COLORS: Record<string, string> = {
  'dev-tablet': '#10B981', // Calibrated Emerald Mint
  'dev-desktop': '#38BDF8', // Precision Azure Blue
  'dev-macbook': '#A855F7', // Cluster Violet
  'dev-phone': '#F59E0B', // Warm Amber
  'dev-server': '#06B6D4', // Cyan Node
};

export const WALLPAPER_PRESETS = [
  {
    id: 'alpine',
    name: 'Precision Obsidian',
    style: {
      backgroundColor: '#090B10',
      backgroundImage: 'radial-gradient(ellipse 70% 60% at 50% -15%, rgba(56, 189, 248, 0.12), rgba(16, 185, 129, 0.05), rgba(9, 11, 16, 0.98))',
    },
  },
  {
    id: 'tokyo-synth',
    name: 'Tokyo Neon Dusk',
    style: {
      backgroundColor: '#0A0518',
      backgroundImage: 'radial-gradient(ellipse 85% 65% at 50% -10%, rgba(255, 42, 133, 0.22), rgba(168, 85, 247, 0.15), rgba(10, 5, 24, 0.98)), linear-gradient(180deg, rgba(16, 8, 38, 0.6) 0%, rgba(10, 5, 24, 1) 100%)',
    },
  },
  {
    id: 'nordic-frost',
    name: 'Nordic Arctic Ice',
    style: {
      backgroundColor: '#EBF3FA',
      backgroundImage: 'radial-gradient(ellipse 90% 70% at 20% -10%, rgba(2, 132, 199, 0.16), rgba(13, 148, 136, 0.10), rgba(235, 243, 250, 0.98)), linear-gradient(180deg, #F0F6FC 0%, #E2ECF7 100%)',
    },
  },
  {
    id: 'deep-nebula',
    name: 'Deep Core Violet',
    style: {
      backgroundColor: '#090A12',
      backgroundImage: 'radial-gradient(ellipse 70% 60% at 80% 20%, rgba(168, 85, 247, 0.14), rgba(56, 189, 248, 0.08), rgba(9, 10, 18, 0.98))',
    },
  },
  {
    id: 'cyber-emerald',
    name: 'Cyber Telemetry',
    style: {
      backgroundColor: '#070E0B',
      backgroundImage: 'radial-gradient(ellipse 80% 50% at 20% 90%, rgba(16, 185, 129, 0.16), rgba(6, 182, 212, 0.04), rgba(7, 14, 11, 0.98))',
    },
  },
  {
    id: 'solar-flare',
    name: 'Amber Glow Workstation',
    style: {
      backgroundColor: '#100C09',
      backgroundImage: 'radial-gradient(ellipse 70% 70% at 50% 10%, rgba(245, 158, 11, 0.14), rgba(244, 63, 94, 0.06), rgba(16, 12, 9, 0.98))',
    },
  },
];

export const INITIAL_APPS: AppItem[] = [
  {
    id: 'settings',
    name: 'System Config',
    iconName: 'Sliders',
    color: '#64748B',
    category: 'tools',
    pageIndex: 0,
  },
  {
    id: 'browser',
    name: 'Browser',
    iconName: 'Globe',
    color: '#38BDF8',
    category: 'productivity',
    packageName: 'com.android.chrome',
    pageIndex: 0,
    isPinned: true,
  },
  {
    id: 'files',
    name: 'Workspace Files',
    iconName: 'Folder',
    color: '#F59E0B',
    category: 'tools',
    packageName: 'com.google.android.documentsui',
    pageIndex: 0,
    isPinned: true,
  },
  {
    id: 'terminal',
    name: 'Console Shell',
    iconName: 'Terminal',
    color: '#10B981',
    category: 'tools',
    pageIndex: 0,
  },
  {
    id: 'notes',
    name: 'Scratchpad',
    iconName: 'FileText',
    color: '#EAB308',
    category: 'productivity',
    packageName: 'com.google.android.keep',
    pageIndex: 0,
    badgeCount: 2,
  },
  {
    id: 'gallery',
    name: 'Media Vault',
    iconName: 'Image',
    color: '#A855F7',
    category: 'media',
    packageName: 'com.google.android.apps.photos',
    pageIndex: 0,
  },
  {
    id: 'music',
    name: 'Audio Lab',
    iconName: 'Music',
    color: '#F43F5E',
    category: 'media',
    packageName: 'com.spotify.music',
    pageIndex: 0,
    badgeCount: 1,
    isPinned: true,
  },
  {
    id: 'camera',
    name: 'Optical Capture',
    iconName: 'Camera',
    color: '#06B6D4',
    category: 'media',
    packageName: 'com.android.camera',
    pageIndex: 0,
  },
  {
    id: 'clock',
    name: 'Precision Clock',
    iconName: 'Clock',
    color: '#F59E0B',
    category: 'tools',
    pageIndex: 0,
  },
  {
    id: 'calculator',
    name: 'Matrix Calc',
    iconName: 'Calculator',
    color: '#10B981',
    category: 'tools',
    pageIndex: 0,
  },
  {
    id: 'calendar',
    name: 'Timeline',
    iconName: 'Calendar',
    color: '#F43F5E',
    category: 'productivity',
    packageName: 'com.google.android.calendar',
    pageIndex: 0,
  },
  {
    id: 'mail',
    name: 'Inbox Feed',
    iconName: 'Mail',
    color: '#38BDF8',
    category: 'productivity',
    packageName: 'com.google.android.gm',
    pageIndex: 0,
    badgeCount: 5,
  },
  {
    id: 'messages',
    name: 'Mesh Comms',
    iconName: 'MessageSquare',
    color: '#10B981',
    category: 'social',
    packageName: 'com.google.android.apps.messaging',
    pageIndex: 1,
    badgeCount: 3,
  },
  {
    id: 'discord',
    name: 'Discord Dev',
    iconName: 'MessageCircle',
    color: '#6366F1',
    category: 'social',
    packageName: 'com.discord',
    pageIndex: 1,
    badgeCount: 12,
  },
  {
    id: 'vscode',
    name: 'VS Code Cloud',
    iconName: 'Code',
    color: '#38BDF8',
    category: 'productivity',
    pageIndex: 1,
  },
  {
    id: 'studio',
    name: 'Mesh Telemetry',
    iconName: 'Cpu',
    color: '#10B981',
    category: 'tools',
    pageIndex: 1,
  },
  {
    id: 'remote-desktop',
    name: 'Node Display',
    iconName: 'Monitor',
    color: '#A855F7',
    category: 'tools',
    pageIndex: 1,
  },
  {
    id: 'gaming-hub',
    name: 'GPU Sandbox',
    iconName: 'Gamepad2',
    color: '#F43F5E',
    category: 'games',
    pageIndex: 1,
  },
];

export const INITIAL_DEVICES: DeviceInfo[] = [
  {
    id: 'dev-tablet',
    name: 'Xiaomi POCO Pad',
    type: 'tablet',
    os: 'Android 14 / HyperOS',
    status: 'online',
    ipAddress: '192.168.1.108',
    resolution: '2560 × 1600 @ 120Hz',
    battery: 92,
    cpuLoad: 16,
    ramUsage: '3.6 / 8.0 GB',
    storage: '64 / 256 GB',
  },
  {
    id: 'dev-desktop',
    name: 'Workstation RIG-01',
    type: 'desktop',
    os: 'Windows 11 Pro (24H2)',
    status: 'online',
    ipAddress: '192.168.1.140',
    resolution: '3840 × 2160 @ 144Hz',
    cpuLoad: 34,
    ramUsage: '18.4 / 64.0 GB',
    storage: '1.2 / 4.0 TB',
  },
  {
    id: 'dev-laptop',
    name: 'MacBook Pro M3 Max',
    type: 'laptop',
    os: 'macOS Sonoma 14.5',
    status: 'online',
    ipAddress: '192.168.1.175',
    resolution: '3024 × 1964 @ 120Hz',
    battery: 88,
    cpuLoad: 12,
    ramUsage: '22.1 / 36.0 GB',
    storage: '320 / 1000 GB',
  },
  {
    id: 'dev-phone',
    name: 'Xiaomi 14 Ultra',
    type: 'phone',
    os: 'Android 14 / HyperOS',
    status: 'standby',
    ipAddress: '192.168.1.192',
    resolution: '3200 × 1440 @ 120Hz',
    battery: 76,
    cpuLoad: 8,
    ramUsage: '4.8 / 16.0 GB',
    storage: '180 / 512 GB',
  },
];

export const INITIAL_PROCESSES: Record<string, ProcessInfo[]> = {
  'dev-desktop': [
    { pid: 4820, name: 'Code.exe', user: 'user', cpu: 14.2, memoryMb: 1420, category: 'user', description: 'Visual Studio Code Workspace' },
    { pid: 7812, name: 'chrome.exe', user: 'user', cpu: 8.6, memoryMb: 2310, category: 'user', description: 'Google Chrome (14 tabs)' },
    { pid: 1204, name: 'docker.exe', user: 'SYSTEM', cpu: 4.1, memoryMb: 3100, category: 'daemon', description: 'Docker Engine Container Host' },
    { pid: 9024, name: 'Spotify.exe', user: 'user', cpu: 2.3, memoryMb: 380, category: 'user', description: 'Spotify Desktop Client' },
    { pid: 3316, name: 'Discord.exe', user: 'user', cpu: 1.8, memoryMb: 490, category: 'user', description: 'Discord Voice & Chat' },
    { pid: 104, name: 'nodus-daemon.exe', user: 'SYSTEM', cpu: 0.5, memoryMb: 48, category: 'daemon', description: 'Nodus Mesh Sync Daemon' },
    { pid: 884, name: 'explorer.exe', user: 'user', cpu: 1.2, memoryMb: 240, category: 'system', description: 'Windows Shell Experience' },
    { pid: 5612, name: 'adb.exe', user: 'user', cpu: 0.2, memoryMb: 34, category: 'daemon', description: 'Android Debug Bridge Server' },
  ],
  'dev-tablet': [
    { pid: 1024, name: 'com.nodus.launcher', user: 'u0_a112', cpu: 4.5, memoryMb: 185, category: 'user', description: 'Nodus Home Primary UI' },
    { pid: 2301, name: 'com.android.systemui', user: 'system', cpu: 3.2, memoryMb: 260, category: 'system', description: 'System UI & Status Bar' },
    { pid: 3410, name: 'com.spotify.music', user: 'u0_a98', cpu: 2.1, memoryMb: 190, category: 'user', description: 'Spotify Audio Service' },
    { pid: 5120, name: 'com.google.android.gms', user: 'system', cpu: 1.8, memoryMb: 320, category: 'service', description: 'Google Play Services' },
    { pid: 6104, name: 'nodus_bridge_agent', user: 'root', cpu: 0.4, memoryMb: 28, category: 'daemon', description: 'Nodus Low-Latency Bridge' },
  ],
  'dev-laptop': [
    { pid: 912, name: 'NodusAgent', user: 'staff', cpu: 0.8, memoryMb: 64, category: 'daemon', description: 'Nodus Node Host' },
    { pid: 1420, name: 'iTerm2', user: 'staff', cpu: 3.2, memoryMb: 220, category: 'user', description: 'Zsh Terminal' },
    { pid: 2190, name: 'Figma', user: 'staff', cpu: 6.4, memoryMb: 1850, category: 'user', description: 'Figma Design App' },
  ],
  'dev-phone': [
    { pid: 801, name: 'system_server', user: 'system', cpu: 2.8, memoryMb: 410, category: 'system', description: 'Android Core Server' },
    { pid: 1102, name: 'nodus_fleet_worker', user: 'u0_a104', cpu: 0.3, memoryMb: 32, category: 'daemon', description: 'Background Fleet Sync' },
  ],
};

export const INITIAL_CLIPBOARD: ClipboardItem[] = [
  {
    id: 'clip-1',
    text: 'ssh user@192.168.1.140 -p 2222',
    sourceDevice: 'dev-desktop',
    deviceName: 'Workstation RIG-01',
    timestamp: Date.now() - 1000 * 60 * 5,
    isPinned: true,
    category: 'code',
  },
  {
    id: 'clip-2',
    text: 'https://github.com/project-nodus/nodus-home',
    sourceDevice: 'dev-tablet',
    deviceName: 'Xiaomi POCO Pad',
    timestamp: Date.now() - 1000 * 60 * 22,
    isPinned: true,
    category: 'link',
  },
  {
    id: 'clip-3',
    text: 'npm run dev -- --host 0.0.0.0 --port 3000',
    sourceDevice: 'dev-laptop',
    deviceName: 'MacBook Pro M3 Max',
    timestamp: Date.now() - 1000 * 60 * 65,
    isPinned: false,
    category: 'code',
  },
  {
    id: 'clip-4',
    text: 'Meeting notes: finalize 120Hz gesture response, optimize Web Audio latency buffer, verify cross-device clip sync.',
    sourceDevice: 'dev-phone',
    deviceName: 'Xiaomi 14 Ultra',
    timestamp: Date.now() - 1000 * 60 * 180,
    isPinned: false,
    category: 'text',
  },
];

export const INITIAL_MUSIC_TRACK: MusicTrack = {
  id: 'track-1',
  title: 'Obsidian Synthesis (120Hz Mix)',
  artist: 'Nodus Audio Lab',
  album: 'HyperOS Ambient',
  durationSec: 245,
  coverColor: '#34C759',
};

export const REMOTE_EXECUTABLES: RemoteExecutable[] = [
  {
    id: 'exec-1',
    name: 'Build Full Cluster',
    description: 'Triggers remote webpack/vite build on RIG-01 workstation',
    deviceId: 'dev-desktop',
    deviceName: 'Workstation RIG-01',
    iconName: 'Layers',
    iconColor: '#007AFF',
    execType: 'command',
    command: 'cd ~/nodus-repo && npm run build',
  },
  {
    id: 'exec-2',
    name: 'Reboot Android Debug Bridge',
    description: 'Restarts adb server and reconnects wireless mesh ports',
    deviceId: 'dev-desktop',
    deviceName: 'Workstation RIG-01',
    iconName: 'RotateCcw',
    iconColor: '#34C759',
    execType: 'command',
    command: 'adb kill-server && adb start-server',
  },
  {
    id: 'exec-3',
    name: 'Clear GPU Cache & Free RAM',
    description: 'Flushes system buffer caches across tablet memory',
    deviceId: 'dev-tablet',
    deviceName: 'Xiaomi POCO Pad',
    iconName: 'Zap',
    iconColor: '#FF9500',
    execType: 'command',
    command: 'sync && echo 3 > /proc/sys/vm/drop_caches',
  },
];
