import { 
  AppItem, 
  NotificationItem, 
  DeviceInfo, 
  DeviceProcess, 
  ClipboardItem,
  NetworkServerConfig,
  WindowsBridgeConfig,
  AndroidBridgeConfig,
  ClipboardSyncConfig,
  RemoteExecutable,
  TrustedDevice
} from '../types/launcher';

export const DEVICE_COLORS: Record<string, string> = {
  'sm-t230nu': '#34C759', // Green (Host Controller)
  'poco-pad': '#007AFF',  // Blue (Secondary Android)
  'main-pc': '#FF9500',   // Orange (Windows 11 Workstation)
  'tab-pc': '#BF5AF2',    // Purple (Windows Touch)
};

export const INITIAL_CLIPBOARD_ITEMS: ClipboardItem[] = [
  {
    id: 'clip-1',
    text: 'https://github.com/developer/android-desktop-cluster',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceColor: '#FF9500',
    type: 'link',
    timestamp: '2m ago',
    pinned: true,
  },
  {
    id: 'clip-2',
    text: 'adb connect 192.168.1.118:5555 && scrcpy -S --stay-awake --turn-screen-off',
    deviceId: 'poco-pad',
    deviceName: 'POCO-PAD',
    deviceType: 'tablet',
    deviceColor: '#007AFF',
    type: 'code',
    timestamp: '14m ago',
    pinned: true,
  },
  {
    id: 'clip-3',
    text: 'Cluster Target: SM-T230NU (Host Node), Windows PC (Bridge Agent 9120), POCO-PAD (Daemon)',
    deviceId: 'sm-t230nu',
    deviceName: 'SM-T230NU',
    deviceType: 'tablet',
    deviceColor: '#34C759',
    type: 'text',
    timestamp: '42m ago',
    pinned: false,
  },
  {
    id: 'clip-4',
    text: 'git commit -m "feat(network): multi-device controller scaffold for Android and Windows"',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceColor: '#FF9500',
    type: 'code',
    timestamp: '1h ago',
    pinned: false,
  },
  {
    id: 'clip-5',
    text: 'Pairing Secret Key: 748-921',
    deviceId: 'tab-pc',
    deviceName: 'TAB PC',
    deviceType: 'laptop',
    deviceColor: '#BF5AF2',
    type: 'snippet',
    timestamp: '3h ago',
    pinned: false,
  },
];

export const INITIAL_DEVICES: DeviceInfo[] = [
  {
    id: 'sm-t230nu',
    name: 'SM-T230NU',
    type: 'tablet',
    os: 'Android 4.4 / LineageOS',
    status: 'connected',
    ipAddress: '192.168.1.104',
    resolution: '1280 × 800 (7.0")',
    battery: 78,
    cpuLoad: 18,
    ramUsage: '1.1 / 1.5 GB',
    storage: '6.2 / 8.0 GB',
  },
  {
    id: 'poco-pad',
    name: 'POCO-PAD',
    type: 'tablet',
    os: 'Xiaomi HyperOS 1.0 (Android 14)',
    status: 'online',
    ipAddress: '192.168.1.118',
    resolution: '2560 × 1600 (12.1" 120Hz)',
    battery: 91,
    cpuLoad: 24,
    ramUsage: '5.2 / 8.0 GB',
    storage: '94 / 256 GB',
  },
  {
    id: 'main-pc',
    name: 'MAIN PC',
    type: 'desktop',
    os: 'Windows 11 Pro 64-bit',
    status: 'online',
    ipAddress: '192.168.1.150',
    resolution: '3840 × 2160 (Dual 4K HDR)',
    cpuLoad: 34,
    ramUsage: '16.4 / 32.0 GB',
    storage: '820 / 2048 GB',
  },
  {
    id: 'tab-pc',
    name: 'TAB PC',
    type: 'laptop',
    os: 'Windows 11 2-in-1 Touch',
    status: 'idle',
    ipAddress: '192.168.1.172',
    resolution: '1920 × 1080 (11.6" Multi-touch)',
    battery: 64,
    cpuLoad: 12,
    ramUsage: '6.1 / 16.0 GB',
    storage: '210 / 512 GB',
  },
];

export const INITIAL_DEVICE_PROCESSES: Record<string, DeviceProcess[]> = {
  'sm-t230nu': [
    { pid: 512, name: 'system_server', user: 'system', cpu: 3.8, memoryMb: 180, status: 'running', category: 'system', description: 'Core Android OS Services' },
    { pid: 834, name: 'com.android.systemui', user: 'u0_a14', cpu: 2.2, memoryMb: 115, status: 'running', category: 'system', description: 'Status Bar & Navigation' },
    { pid: 180, name: 'surfaceflinger', user: 'system', cpu: 4.6, memoryMb: 62, status: 'running', category: 'system', description: 'Display Compositor Engine' },
    { pid: 2410, name: 'com.android.browser', user: 'u0_a45', cpu: 5.1, memoryMb: 165, status: 'running', category: 'user', description: 'Stock Web Browser' },
    { pid: 1140, name: 'com.cyanogenmod.trebuchet', user: 'u0_a8', cpu: 1.2, memoryMb: 85, status: 'running', category: 'user', description: 'LineageOS Homescreen Launcher' },
    { pid: 910, name: 'com.android.phone', user: 'radio', cpu: 0.4, memoryMb: 48, status: 'running', category: 'service', description: 'Telephony & Connectivity Daemon' },
    { pid: 214, name: 'mediaserver', user: 'media', cpu: 1.5, memoryMb: 54, status: 'running', category: 'daemon', description: 'Audio & Video Decoder Service' },
    { pid: 1980, name: 'com.android.settings', user: 'system', cpu: 0.2, memoryMb: 42, status: 'sleeping', category: 'user', description: 'Device Configuration Host' },
    { pid: 340, name: 'wpa_supplicant', user: 'wifi', cpu: 0.2, memoryMb: 14, status: 'running', category: 'daemon', description: 'Wi-Fi 802.11 Protocol Handler' },
    { pid: 204, name: 'adbd', user: 'root', cpu: 0.3, memoryMb: 18, status: 'running', category: 'daemon', description: 'Android Debug Bridge Daemon' },
  ],
  'poco-pad': [
    { pid: 1420, name: 'system_server', user: 'system', cpu: 3.5, memoryMb: 420, status: 'running', category: 'system', description: 'Android 14 Framework Services' },
    { pid: 2390, name: 'com.miui.home', user: 'u0_a22', cpu: 3.8, memoryMb: 380, status: 'running', category: 'user', description: 'HyperOS Desktop & Gestures' },
    { pid: 2100, name: 'com.android.systemui', user: 'u0_a18', cpu: 2.1, memoryMb: 290, status: 'running', category: 'system', description: 'Control Center & 120Hz UI' },
    { pid: 650, name: 'surfaceflinger', user: 'system', cpu: 6.2, memoryMb: 210, status: 'running', category: 'system', description: '2.5K Hardware Compositor' },
    { pid: 5410, name: 'com.android.chrome', user: 'u0_a89', cpu: 7.8, memoryMb: 520, status: 'running', category: 'user', description: 'Chrome Tabs & Renderers' },
    { pid: 6210, name: 'com.spotify.music', user: 'u0_a104', cpu: 2.4, memoryMb: 240, status: 'running', category: 'user', description: 'Background Audio Streamer' },
    { pid: 3140, name: 'com.google.android.gms', user: 'u0_a9', cpu: 3.2, memoryMb: 310, status: 'running', category: 'service', description: 'Google Play Services Engine' },
    { pid: 1890, name: 'miui.daemon', user: 'system', cpu: 1.1, memoryMb: 140, status: 'running', category: 'daemon', description: 'HyperOS Optimization Daemon' },
    { pid: 1720, name: 'com.xiaomi.hyperos.display', user: 'system', cpu: 2.0, memoryMb: 175, status: 'running', category: 'service', description: 'Adaptive Refresh Rate Controller' },
    { pid: 310, name: 'logd', user: 'logd', cpu: 0.3, memoryMb: 32, status: 'running', category: 'daemon', description: 'System Logging Buffer' },
  ],
  'main-pc': [
    { pid: 4, name: 'System', user: 'NT AUTHORITY\\SYSTEM', cpu: 1.1, memoryMb: 180, status: 'running', category: 'system', description: 'Windows 11 NT Kernel & Drivers' },
    { pid: 1204, name: 'dwm.exe', user: 'Window Manager\\DWM-1', cpu: 4.2, memoryMb: 420, status: 'running', category: 'system', description: 'Desktop Window Manager (Dual 4K)' },
    { pid: 4892, name: 'explorer.exe', user: 'USER-ADMIN', cpu: 1.8, memoryMb: 340, status: 'running', category: 'user', description: 'Windows Shell & Taskbar' },
    { pid: 8312, name: 'msedge.exe', user: 'USER-ADMIN', cpu: 8.9, memoryMb: 1850, status: 'running', category: 'user', description: 'Microsoft Edge GPU Acceleration' },
    { pid: 11240, name: 'Code.exe', user: 'USER-ADMIN', cpu: 6.4, memoryMb: 1420, status: 'running', category: 'user', description: 'VS Code IDE Workspace & Language Server' },
    { pid: 9104, name: 'Discord.exe', user: 'USER-ADMIN', cpu: 3.1, memoryMb: 620, status: 'running', category: 'user', description: 'Discord Voice & Video Client' },
    { pid: 7420, name: 'steam.exe', user: 'USER-ADMIN', cpu: 1.6, memoryMb: 380, status: 'running', category: 'user', description: 'Steam Client WebHelper' },
    { pid: 2412, name: 'nvcontainer.exe', user: 'NT AUTHORITY\\SYSTEM', cpu: 2.8, memoryMb: 480, status: 'running', category: 'service', description: 'NVIDIA GPU Display Driver Container' },
    { pid: 13980, name: 'WindowsTerminal.exe', user: 'USER-ADMIN', cpu: 1.4, memoryMb: 210, status: 'running', category: 'user', description: 'PowerShell 7.4 Console' },
    { pid: 5120, name: 'SearchHost.exe', user: 'USER-ADMIN', cpu: 0.4, memoryMb: 190, status: 'sleeping', category: 'daemon', description: 'Windows Search & Indexer' },
    { pid: 1840, name: 'spoolsv.exe', user: 'SYSTEM', cpu: 0.1, memoryMb: 45, status: 'sleeping', category: 'service', description: 'Print Spooler Service' },
  ],
  'tab-pc': [
    { pid: 4, name: 'System', user: 'NT AUTHORITY\\SYSTEM', cpu: 0.8, memoryMb: 140, status: 'running', category: 'system', description: 'Windows 11 Kernel' },
    { pid: 1088, name: 'dwm.exe', user: 'Window Manager\\DWM-1', cpu: 2.9, memoryMb: 290, status: 'running', category: 'system', description: 'Desktop Window Manager' },
    { pid: 3840, name: 'explorer.exe', user: 'USER-TAB', cpu: 1.6, memoryMb: 240, status: 'running', category: 'user', description: 'Touch-Optimized Windows Shell' },
    { pid: 7210, name: 'chrome.exe', user: 'USER-TAB', cpu: 6.9, memoryMb: 1100, status: 'running', category: 'user', description: 'Google Chrome Web Browser' },
    { pid: 4510, name: 'TabTip.exe', user: 'USER-TAB', cpu: 1.1, memoryMb: 160, status: 'running', category: 'service', description: 'Touch Keyboard and Handwriting Panel' },
    { pid: 6190, name: 'OneDrive.exe', user: 'USER-TAB', cpu: 0.7, memoryMb: 180, status: 'running', category: 'daemon', description: 'Microsoft Cloud Sync' },
    { pid: 2980, name: 'PenTabletService.exe', user: 'SYSTEM', cpu: 0.5, memoryMb: 95, status: 'running', category: 'service', description: 'Stylus Digitizer Pressure Driver' },
    { pid: 8820, name: 'Spotify.exe', user: 'USER-TAB', cpu: 2.0, memoryMb: 310, status: 'running', category: 'user', description: 'Spotify Desktop Player' },
  ],
};

export const INITIAL_APPS: AppItem[] = [
  // Page 0 Main Grid - Real Operational Launcher & Controller Apps
  { id: 'settings', name: 'Settings & Hub', iconName: 'Settings', color: '#34C759', category: 'system', pageIndex: 0, order: 0 },
  { id: 'studio', name: 'Dual-Platform Studio', iconName: 'Code', color: '#5856D6', category: 'tools', pageIndex: 0, order: 1 },
  { id: 'terminal', name: 'Remote Terminal', iconName: 'Terminal', color: '#007AFF', category: 'tools', pageIndex: 0, order: 2 },
  { id: 'monitor', name: 'Process Monitor', iconName: 'Activity', color: '#FF3B30', category: 'system', pageIndex: 0, order: 3 },
  { id: 'files', name: 'Cluster Explorer', iconName: 'HardDrive', color: '#007AFF', category: 'tools', pageIndex: 0, order: 4 },
  { id: 'network', name: 'Mesh Network', iconName: 'Radio', color: '#64D2FF', category: 'tools', pageIndex: 0, order: 5 },
  { id: 'clipboard', name: 'Fleet Clipboard', iconName: 'Clipboard', color: '#FF9500', category: 'tools', pageIndex: 0, order: 6 },
];

export const DOCK_APP_IDS = ['settings', 'studio', 'terminal', 'monitor', 'files', 'network', 'clipboard'];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    appId: 'settings',
    appName: 'Fleet Hub',
    title: 'Cluster Server Active',
    message: 'WebSocket Hub listening on 192.168.1.104:8890',
    time: '2m ago',
    read: false,
    iconName: 'Server',
    color: '#34C759',
  },
  {
    id: 'notif-2',
    appId: 'terminal',
    appName: 'Remote Bridge',
    title: 'Windows Agent Connected',
    message: 'MAIN PC (192.168.1.150:9120) ready for remote execution',
    time: '8m ago',
    read: false,
    iconName: 'Terminal',
    color: '#007AFF',
  },
  {
    id: 'notif-3',
    appId: 'settings',
    appName: 'Clipboard Sync',
    title: 'Clipboard Linked',
    message: '2-way clipboard sync active across 4 nodes',
    time: '25m ago',
    read: true,
    iconName: 'Clipboard',
    color: '#FF9500',
  },
];

export const WALLPAPER_PRESETS = [
  {
    id: 'alpine-horizon',
    name: 'Alpine Dusk',
    bgClass: 'bg-cover bg-center',
    preview: '#3B5998',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.4), rgba(10, 10, 12, 0.65)), url('https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'material-fluid',
    name: 'Material Waves',
    bgClass: 'bg-cover bg-center',
    preview: '#2D3748',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.35), rgba(10, 10, 12, 0.6)), url('https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'sunset-dune',
    name: 'Desert Mirage',
    bgClass: 'bg-cover bg-center',
    preview: '#C05621',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.35), rgba(10, 10, 12, 0.6)), url('https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'forest-mist',
    name: 'Nordic Forest',
    bgClass: 'bg-cover bg-center',
    preview: '#22543D',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.4), rgba(10, 10, 12, 0.65)), url('https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'nordic-aurora',
    name: 'Polar Aurora',
    bgClass: 'bg-cover bg-center',
    preview: '#234E52',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.35), rgba(10, 10, 12, 0.6)), url('https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'cyber-grid',
    name: 'Cosmic Nebula',
    bgClass: 'bg-cover bg-center',
    preview: '#44337A',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.4), rgba(10, 10, 12, 0.65)), url('https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'geometric-pastel',
    name: 'Minimal Architecture',
    bgClass: 'bg-cover bg-center',
    preview: '#4A5568',
    style: {
      backgroundImage: `linear-gradient(rgba(10, 10, 12, 0.4), rgba(10, 10, 12, 0.65)), url('https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=2000&q=80')`,
      backgroundSize: 'cover',
      backgroundPosition: 'center',
    },
  },
  {
    id: 'amoled-black',
    name: 'Clean Obsidian',
    bgClass: 'bg-[#0A0A0C]',
    preview: '#0A0A0C',
    style: { background: '#0A0A0C' },
  },
];

export const INITIAL_SERVER_CONFIG: NetworkServerConfig = {
  role: 'host',
  serverPort: 8890,
  serverHost: '192.168.1.104',
  autoDiscover: true,
  heartbeatIntervalMs: 5000,
  pairingSecret: '748-921',
  encryptionEnabled: true,
  autoStartOnBoot: true,
  broadcastMdns: true,
  serverStatus: 'running',
};

export const INITIAL_WINDOWS_BRIDGE: WindowsBridgeConfig = {
  agentInstalled: true,
  bridgePort: 9120,
  authToken: 'win-bridge-sec-token-894',
  allowRemotePower: true,
  allowProcessTermination: true,
  allowElevatedCommands: false,
  allowedExecutablesPath: 'C:\\Program Files;C:\\Tools;C:\\Windows\\System32',
  syncVolumeAndMedia: true,
  connectedHost: '192.168.1.150',
};

export const INITIAL_ANDROID_BRIDGE: AndroidBridgeConfig = {
  companionInstalled: true,
  accessibilityServiceGranted: true,
  notificationSync: true,
  allowIntentBroadcasts: true,
  allowDeviceActions: true,
  syncBatteryAndSensors: true,
};

export const INITIAL_CLIPBOARD_SYNC_CONFIG: ClipboardSyncConfig = {
  enabled: true,
  syncMode: 'bidirectional',
  historyLimit: 50,
  retentionHours: 24,
  filterPasswords: true,
  syncImages: true,
  maxPayloadSizeKb: 2048,
  autoClearSensitiveMinutes: 15,
};

export const INITIAL_TRUSTED_DEVICES: TrustedDevice[] = [
  {
    id: 'sm-t230nu',
    name: 'SM-T230NU (Host Controller)',
    os: 'android',
    ip: '192.168.1.104',
    fingerprint: 'SHA256:7B:3A:99:C1:20:FE:44:88',
    isTrusted: true,
    lastSeen: 'Active Now',
    permissions: {
      remoteExec: true,
      clipboardSync: true,
      processKill: true,
      powerControl: true,
    },
  },
  {
    id: 'main-pc',
    name: 'MAIN PC (Windows 11)',
    os: 'windows',
    ip: '192.168.1.150',
    fingerprint: 'SHA256:4C:82:11:A9:90:3E:AA:12',
    isTrusted: true,
    lastSeen: '1m ago',
    permissions: {
      remoteExec: true,
      clipboardSync: true,
      processKill: true,
      powerControl: true,
    },
  },
  {
    id: 'poco-pad',
    name: 'POCO-PAD (HyperOS)',
    os: 'android',
    ip: '192.168.1.118',
    fingerprint: 'SHA256:19:FC:83:55:A2:11:66:3D',
    isTrusted: true,
    lastSeen: '3m ago',
    permissions: {
      remoteExec: true,
      clipboardSync: true,
      processKill: true,
      powerControl: false,
    },
  },
  {
    id: 'tab-pc',
    name: 'TAB PC (Windows Touch)',
    os: 'windows',
    ip: '192.168.1.172',
    fingerprint: 'SHA256:E0:44:77:99:01:BC:48:9A',
    isTrusted: true,
    lastSeen: '12m ago',
    permissions: {
      remoteExec: true,
      clipboardSync: true,
      processKill: false,
      powerControl: true,
    },
  },
];

export const INITIAL_REMOTE_EXECUTABLES: RemoteExecutable[] = [
  // Windows PC Remote Executables
  {
    id: 'win-exec-1',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceOs: 'windows',
    name: 'Visual Studio Code',
    description: 'Launch VS Code workspace on Windows Desktop',
    category: 'productivity',
    iconName: 'Code',
    iconColor: '#007ACC',
    execType: 'command',
    commandOrPackage: 'code .',
    workingDir: 'C:\\Projects',
    runAsAdmin: false,
    enabled: true,
    pinnedToDrawer: true,
    lastExecuted: '20m ago',
  },
  {
    id: 'win-exec-2',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceOs: 'windows',
    name: 'Windows Terminal (Admin)',
    description: 'Elevated PowerShell CLI prompt',
    category: 'tools',
    iconName: 'Terminal',
    iconColor: '#4E75F8',
    execType: 'command',
    commandOrPackage: 'wt.exe -p "PowerShell"',
    runAsAdmin: true,
    enabled: true,
    pinnedToDrawer: true,
    lastExecuted: '1h ago',
  },
  {
    id: 'win-exec-3',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceOs: 'windows',
    name: 'Steam Big Picture',
    description: 'Launch Steam client in Controller Gaming UI',
    category: 'games',
    iconName: 'Gamepad2',
    iconColor: '#1B2838',
    execType: 'url_protocol',
    commandOrPackage: 'steam://open/bigpicture',
    enabled: true,
    pinnedToDrawer: true,
    lastExecuted: 'Yesterday',
  },
  {
    id: 'win-exec-4',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceOs: 'windows',
    name: 'Lock Windows Workstation',
    description: 'Instant Lock Workstation Screen (rundll32.exe)',
    category: 'system',
    iconName: 'Lock',
    iconColor: '#FF9500',
    execType: 'command',
    commandOrPackage: 'rundll32.exe user32.dll,LockWorkStation',
    enabled: true,
    pinnedToDrawer: false,
  },
  {
    id: 'win-exec-5',
    deviceId: 'main-pc',
    deviceName: 'MAIN PC',
    deviceType: 'desktop',
    deviceOs: 'windows',
    name: 'Spotify Desktop Player',
    description: 'Start Spotify desktop background service',
    category: 'media',
    iconName: 'Music',
    iconColor: '#1DB954',
    execType: 'url_protocol',
    commandOrPackage: 'spotify:',
    enabled: true,
    pinnedToDrawer: true,
  },

  // Remote Android Executables (POCO-PAD)
  {
    id: 'and-exec-1',
    deviceId: 'poco-pad',
    deviceName: 'POCO-PAD',
    deviceType: 'tablet',
    deviceOs: 'android',
    name: 'Remote Camera Shutter',
    description: 'Trigger rear sensor high-res photo capture',
    category: 'tools',
    iconName: 'Camera',
    iconColor: '#007AFF',
    execType: 'intent',
    commandOrPackage: 'android.media.action.STILL_IMAGE_CAMERA',
    enabled: true,
    pinnedToDrawer: true,
    lastExecuted: '45m ago',
  },
  {
    id: 'and-exec-2',
    deviceId: 'poco-pad',
    deviceName: 'POCO-PAD',
    deviceType: 'tablet',
    deviceOs: 'android',
    name: 'YouTube Kids / Player',
    description: 'Launch YouTube app intent on tablet display',
    category: 'media',
    iconName: 'PlaySquare',
    iconColor: '#FF0000',
    execType: 'native_app',
    commandOrPackage: 'com.google.android.youtube',
    enabled: true,
    pinnedToDrawer: true,
  },
  {
    id: 'and-exec-3',
    deviceId: 'poco-pad',
    deviceName: 'POCO-PAD',
    deviceType: 'tablet',
    deviceOs: 'android',
    name: 'Toggle Portable WiFi Hotspot',
    description: 'Enable / Disable tethered 5G hotspot broadcast',
    category: 'system',
    iconName: 'Wifi',
    iconColor: '#34C759',
    execType: 'intent',
    commandOrPackage: 'nova.intent.action.TOGGLE_TETHERING',
    enabled: true,
    pinnedToDrawer: false,
  },
];
